name: Build Elevnety

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build using node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - run: npm install
      - name: npm eleventy
        run: npx eleventy --version # Ensure eleventy is installed and executable
      - run: npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_DIR: public
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}